<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Finance manager: <?php echo($this->title) ?></title>
        
        <?php
        	echo $this->headLink()
        		->prependStylesheet($this->basePath() . '/css/default.css') ?> 
       
    </head>
    <body>
        <div id="title"><h1>Budget application</h1></div>
		
        <div id="menu">
            <ul>
                <li><a href="<?php echo $this->basePath() . '/index' ?>">Home</a></li>                
                <li><a href="<?php echo $this->basePath() . '/transaction/list' ?>">Transactions</a>
                (<a href="<?php echo($this->basePath() . '/transaction/byMonth') ?>">by month</a>)
                </li>
                </ul>
        </div>
        
        <div id="main-area">
        	<?php echo $this->content ?>
        </div>
    </body>
</html>