<?php 
	function write_subtotal($date, $amount) {
		echo('<tr style="border-top: 1px solid #000000"><td></td><td colspan="3"</td><td style="text-align: right;"><i>&euro; ' . sprintf('%.2f', $amount / 100.0) . '</i><br />&nbsp;</td><td></td></tr>');
	}
?>

<script>
	function delete_transaction(id) 
	{
		if(!confirm('Are you sure you want to delete this transaction?'))
			return;
		
		var http = new XMLHttpRequest();
		var url = '<?php echo $this->basePath() . '/transaction/delete/id/'; ?>' + id;
		var params = 'confirm=yes';

		http.open('POST', url, true);
		http.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
		http.setRequestHeader('Content-length', params.length);
		http.setRequestHeader('Connection', 'close');

		http.onreadystatechange = function() {
			if(http.readyState == 4) {
				document.location = '<?php echo $this->basePath() . '/transaction/list'; ?>';
			}
		}
		
		http.send(params);	
	}
</script>

<style>
	div#week_overview {
		float:left; 
		width: 75%;
	}

	span#week_number {
		font-size: larger; 
		font-weight: bold; 
		padding-bottom: 5px; 
		display: block;	
	}
	
	span#week_dates {
		font-size: small; 
		display: block; 
		padding-bottom: 10px;
	}
</style>

<div id="week_overview">
	<!-- Warning: this doesn't take first and last week into account -->
	<span id="week_number">
		<a href="<?php echo $this->basePath() . '/transaction/list/week/' . ($this->week - 1) . '/year/' . $this->year ?>">&lt;&lt;</a>
		Week <?php echo $this->week; ?>
		<a href="<?php echo $this->basePath() . '/transaction/list/week/' . ($this->week + 1) . '/year/' . $this->year ?>">&gt;&gt;</a>
	</span>
	
	<span id="week_dates">
		<?=date('F j, Y', $this->timespan[0])?>
		to
		<?=date('F j, Y', $this->timespan[1])?>
	</span>
	
	<table class="table-hover">
		<thead>
		<tr>
			<th>Date</th>
			<th>Category</th>
			<th>Subcategory</th>
			<th>Description</th>
			<th>Amount</th>
			<th></th>
		</tr>		
		</thead>

		<tbody>		
<?php
	$subtotal = 0;
	$timestamp = '';

	foreach($this->transactions as $row)
	{
		
		if($timestamp == '') $timestamp = $row['timestamp'];
		
		if($timestamp <> $row['timestamp']) {
			write_subtotal($timestamp, $subtotal);
			$timestamp = $row['timestamp'];
			$subtotal = 0;
		}
?>
			<tr>
				<td><?=$row['timestamp']?></td>
				<td><?=$row['category']?></td>
				<td><?=$row['subcategory']?></td>
				<td><?=$row['description']?></td>
				<td style="text-align: right;">&euro; <?=sprintf('%.02f', $row['amount'] / 100.0)?></td>
				<td><a href="javascript:delete_transaction(<?php echo $row['id'] ?>);"><img style="width:24px" src="<?php echo $this->basePath() . '/img/icons/delete.svg' ?>"</a></td>				
			</tr>	
<?php
		$subtotal += $row['amount'];
	}
	
	write_subtotal($timestamp, $subtotal);
?>		
		</tbody>
	<tfoot>
		<tr>		
			<td colspan="6">
			<a href="<?php echo($this->basePath() . '/transaction/add'); ?>">Add new transactions</a>
			</td>
		</tr>
	</tfoot>
		
	</table>


</div>

<div style="float: right">

<table class="table-hover">
<?php
	$periods = array_keys($this->overview);

	foreach($periods as $period) {
?>
		<tr><td colspan="2">
			<b>Week <?php echo(floor($period / 100)); ?> / <?php echo($period % 100); ?> </b>
		</td></tr>
<?php
		$data = $this->overview[$period];
		$total = 0;
	
		foreach($data as $row) {
?>
			<tr>
				<td><?php echo($row['category']); ?></td>
				<td style="text-align: right;">&euro; <?php echo(sprintf('%.2f', $row['total'] / 100.0)); ?></td>
			</tr>
<?php
			$total += $row['total'];
		}

		echo('<tr style="border-top: 1px solid #000000"><td></td><td style="text-align: right;">&euro; ' . sprintf('%.2f', $total / 100.0) . '</td></tr>');		
	}
?>
</table>
